spring:
    datasource:
      url: jdbc:mysql://localhost:3306/test
      username: test
      password: tjdrud123!
      driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      properties:
        hibernate:
          show_sql: true
          ddl-auto: create
server:
  error:
    include-message: always
    #include-binding-errors: always 바인딩 에러 포함